In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('noise_level_data.csv')
df.head()

   noise level   label
0          61.1      0
1          61.9      0
2          61.5      0
3          60.7      0
4          59.4      0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 417000 entries, 0 to 416999
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   noise level   417000 non-null  float64
 1   label         417000 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 6.4 MB

In [4]:
df.describe()

        noise level           label
count  417000.000000  417000.000000
mean       47.496242       0.037341
std        11.211426       0.189595
min        18.700000       0.000000
25%        40.200000       0.000000
50%        47.900000       0.000000
75%        56.900000       0.000000
max        92.200000       1.000000

In [ ]:
X, y = df.drop('noise level ', axis=1), df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.